In [29]:
import pandas as pd
import pathlib
from sklearn import preprocessing
import numpy as np
import random

In [2]:
prices = pd.read_csv('../../data/854_1575_bundle_archive/prices-split-adjusted.csv')
prices

,date,symbol,open,close,low,high,volume
0,2016-01-05,WLTW,123.430000,125.839996,122.309998,126.250000,2163600.0
1,2016-01-06,WLTW,125.239998,119.980003,119.940002,125.540001,2386400.0
2,2016-01-07,WLTW,116.379997,114.949997,114.930000,119.739998,2489500.0
3,2016-01-08,WLTW,115.480003,116.620003,113.500000,117.440002,2006300.0
4,2016-01-11,WLTW,117.010002,114.970001,114.089996,117.330002,1408600.0
...,...,...,...,...,...,...,...
851259,2016-12-30,ZBH,103.309998,103.199997,102.849998,103.930000,973800.0
851260,2016-12-30,ZION,43.070000,43.040001,42.689999,43.310001,1938100.0
851261,2016-12-30,ZTS,53.639999,53.529999,53.270000,53.740002,1701200.0
851262,2016-12-30,AIV,44.730000,45.450001,44.410000,45.590000,1380900.0
851263,2016-12-30,FTV,54.200001,53.630001,53.389999,54.480000,705100.0

In [3]:
prices.date[0]

'2016-01-05'

In [4]:
prices["year"] = prices.date.str[:4]

In [5]:
prices.year

0         2016
1         2016
2         2016
3         2016
4         2016
          ...
851259    2016
851260    2016
851261    2016
851262    2016
851263    2016
Name: year, Length: 851264, dtype: object

In [6]:
min(prices.date)

'2010-01-04'

In [7]:
details = pd.read_csv('../../data/854_1575_bundle_archive/securities.csv')
details[["Ticker symbol","GICS Sector","GICS Sub Industry"]]

    Ticker symbol             GICS Sector               GICS Sub Industry
0             MMM             Industrials        Industrial Conglomerates
1             ABT             Health Care           Health Care Equipment
2            ABBV             Health Care                 Pharmaceuticals
3             ACN  Information Technology  IT Consulting & Other Services
4            ATVI  Information Technology     Home Entertainment Software
..            ...                     ...                             ...
500          YHOO  Information Technology    Internet Software & Services
501           YUM  Consumer Discretionary                     Restaurants
502           ZBH             Health Care           Health Care Equipment
503          ZION              Financials                  Regional Banks
504           ZTS             Health Care                 Pharmaceuticals

[505 rows x 3 columns]

In [8]:
len(details["GICS Sector"].unique())

11

In [9]:
len(details["GICS Sub Industry"].unique())

124

In [10]:
fundamentals = pd.read_csv('../../data/854_1575_bundle_archive/fundamentals.csv')
fundamentals = fundamentals.drop(columns=fundamentals.columns[0]).dropna()
fundamentals["Key"] = fundamentals["Ticker Symbol"]+fundamentals["For Year"].astype(int).astype(str)
fundamentals = fundamentals.drop(columns="Ticker Symbol")
fundamentals = fundamentals.drop(columns="Period Ending")
fundamentals = fundamentals.drop(columns="For Year")
fundamentals

,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,Cash and Cash Equivalents,Changes in Inventories,Common Stocks,...,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,Earnings Per Share,Estimated Shares Outstanding,Key
0,3.068000e+09,-222000000.0,-1.961000e+09,23.0,-1.888000e+09,4.695000e+09,53.0,1.330000e+09,0.0,127000000.0,...,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-3.670000e+08,-5.60,3.350000e+08,AAL2012
1,4.975000e+09,-93000000.0,-2.723000e+09,67.0,-3.114000e+09,1.059200e+10,75.0,2.175000e+09,0.0,5000000.0,...,1.432300e+10,1.380600e+10,-2.731000e+09,4.500900e+10,4.227800e+10,2.674300e+10,0.000000e+00,-11.25,1.630222e+08,AAL2013
2,4.668000e+09,-160000000.0,-1.500000e+08,143.0,-5.311000e+09,1.513500e+10,60.0,1.768000e+09,0.0,7000000.0,...,1.175000e+10,1.340400e+10,2.021000e+09,4.120400e+10,4.322500e+10,4.265000e+10,0.000000e+00,4.02,7.169154e+08,AAL2014
3,5.102000e+09,352000000.0,-7.080000e+08,135.0,-6.151000e+09,1.159100e+10,51.0,1.085000e+09,0.0,6000000.0,...,9.985000e+09,1.360500e+10,5.635000e+09,4.278000e+10,4.841500e+10,4.099000e+10,0.000000e+00,11.39,6.681299e+08,AAL2015
4,2.409453e+09,-89482000.0,6.000000e+05,32.0,-2.711820e+08,5.202150e+08,23.0,5.981110e+08,-260298000.0,7000.0,...,3.184200e+09,2.559638e+09,1.210694e+09,3.403120e+09,4.613814e+09,6.205003e+09,-2.709500e+07,5.29,7.328355e+07,AAP2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1771,2.255000e+08,-40400000.0,-3.480000e+07,11.0,-3.423000e+08,4.330700e+09,166.0,1.083300e+09,-164600000.0,2700000.0,...,4.313300e+09,1.024000e+09,6.549900e+09,3.108100e+09,9.658000e+09,4.673300e+09,-6.183700e+09,4.26,1.690845e+08,ZBH2014
1772,4.320000e+08,-56100000.0,-2.750000e+07,1.0,-4.341000e+08,8.195300e+09,100.0,1.459300e+09,-205400000.0,3000000.0,...,5.862900e+09,1.617900e+09,9.887900e+09,1.733160e+10,2.721950e+10,5.997800e+09,-6.329100e+09,0.78,1.884615e+08,ZBH2015
1777,1.381000e+09,-99000000.0,9.000000e+06,54.0,-1.840000e+08,8.780000e+08,43.0,6.100000e+08,-178000000.0,5000000.0,...,3.357000e+09,1.415000e+09,9.400000e+08,5.618000e+09,6.558000e+09,4.561000e+09,0.000000e+00,1.01,4.990099e+08,ZTS2013
1778,1.071000e+09,69000000.0,-7.000000e+06,44.0,-1.800000e+08,9.580000e+08,81.0,8.820000e+08,-110000000.0,5000000.0,...,3.465000e+09,1.086000e+09,1.311000e+09,5.277000e+09,6.588000e+09,4.785000e+09,0.000000e+00,1.16,5.025862e+08,ZTS2014
1779,1.313000e+09,-58000000.0,-8.100000e+07,32.0,-2.240000e+08,1.012000e+09,65.0,1.154000e+09,-262000000.0,5000000.0,...,3.830000e+09,1.781000e+09,1.068000e+09,6.845000e+09,7.913000e+09,4.765000e+09,-2.030000e+08,0.68,4.985294e+08,ZTS2015

In [11]:
fundamentals["Key"]

0       AAL2012
1       AAL2013
2       AAL2014
3       AAL2015
4       AAP2012
         ...
1771    ZBH2014
1772    ZBH2015
1777    ZTS2013
1778    ZTS2014
1779    ZTS2015
Name: Key, Length: 1299, dtype: object

In [12]:
prices["Key"] = prices.symbol+prices.year
#prices = prices.drop(columns="symbol")
#prices = prices.drop(columns="date")

In [13]:
prices["Key"]

0         WLTW2016
1         WLTW2016
2         WLTW2016
3         WLTW2016
4         WLTW2016
            ...
851259     ZBH2016
851260    ZION2016
851261     ZTS2016
851262     AIV2016
851263     FTV2016
Name: Key, Length: 851264, dtype: object

In [14]:
prices

,date,symbol,open,close,low,high,volume,year,Key
0,2016-01-05,WLTW,123.430000,125.839996,122.309998,126.250000,2163600.0,2016,WLTW2016
1,2016-01-06,WLTW,125.239998,119.980003,119.940002,125.540001,2386400.0,2016,WLTW2016
2,2016-01-07,WLTW,116.379997,114.949997,114.930000,119.739998,2489500.0,2016,WLTW2016
3,2016-01-08,WLTW,115.480003,116.620003,113.500000,117.440002,2006300.0,2016,WLTW2016
4,2016-01-11,WLTW,117.010002,114.970001,114.089996,117.330002,1408600.0,2016,WLTW2016
...,...,...,...,...,...,...,...,...,...
851259,2016-12-30,ZBH,103.309998,103.199997,102.849998,103.930000,973800.0,2016,ZBH2016
851260,2016-12-30,ZION,43.070000,43.040001,42.689999,43.310001,1938100.0,2016,ZION2016
851261,2016-12-30,ZTS,53.639999,53.529999,53.270000,53.740002,1701200.0,2016,ZTS2016
851262,2016-12-30,AIV,44.730000,45.450001,44.410000,45.590000,1380900.0,2016,AIV2016
851263,2016-12-30,FTV,54.200001,53.630001,53.389999,54.480000,705100.0,2016,FTV2016

In [15]:
data = prices.merge(fundamentals, on='Key')
data

,date,symbol,open,close,low,high,volume,year,Key,Accounts Payable,...,Total Assets,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,Earnings Per Share,Estimated Shares Outstanding
0,2012-01-03,AAL,5.200000,5.120000,5.070000,5.220000,6105900.0,2012,AAL2012,3.068000e+09,...,2.351000e+10,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-367000000.0,-5.60,3.350000e+08
1,2012-01-04,AAL,5.090000,5.030000,4.970000,5.180000,5268700.0,2012,AAL2012,3.068000e+09,...,2.351000e+10,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-367000000.0,-5.60,3.350000e+08
2,2012-01-05,AAL,5.150000,5.470000,5.070000,5.480000,8216100.0,2012,AAL2012,3.068000e+09,...,2.351000e+10,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-367000000.0,-5.60,3.350000e+08
3,2012-01-06,AAL,5.440000,5.600000,5.400000,5.670000,8323000.0,2012,AAL2012,3.068000e+09,...,2.351000e+10,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-367000000.0,-5.60,3.350000e+08
4,2012-01-09,AAL,5.560000,5.720000,5.550000,5.800000,8029900.0,2012,AAL2012,3.068000e+09,...,2.351000e+10,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-367000000.0,-5.60,3.350000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323947,2016-12-23,XLNX,60.380001,60.560001,60.080002,60.570000,1105700.0,2016,XLNX2016,3.072220e+08,...,4.823154e+09,3.918933e+09,9.460860e+08,2.589893e+09,2.233261e+09,4.823154e+09,2.213881e+09,0.0,2.14,2.574145e+08
323948,2016-12-27,XLNX,61.070000,61.240002,60.889999,61.580002,1594400.0,2016,XLNX2016,3.072220e+08,...,4.823154e+09,3.918933e+09,9.460860e+08,2.589893e+09,2.233261e+09,4.823154e+09,2.213881e+09,0.0,2.14,2.574145e+08
323949,2016-12-28,XLNX,62.139999,60.630001,60.590000,62.240002,2141000.0,2016,XLNX2016,3.072220e+08,...,4.823154e+09,3.918933e+09,9.460860e+08,2.589893e+09,2.233261e+09,4.823154e+09,2.213881e+09,0.0,2.14,2.574145e+08
323950,2016-12-29,XLNX,60.599998,60.740002,60.360001,61.119999,1398100.0,2016,XLNX2016,3.072220e+08,...,4.823154e+09,3.918933e+09,9.460860e+08,2.589893e+09,2.233261e+09,4.823154e+09,2.213881e+09,0.0,2.14,2.574145e+08
323951,2016-12-30,XLNX,61.090000,60.369999,60.020000,61.480000,2111700.0,2016,XLNX2016,3.072220e+08,...,4.823154e+09,3.918933e+09,9.460860e+08,2.589893e+09,2.233261e+09,4.823154e+09,2.213881e+09,0.0,2.14,2.574145e+08

In [16]:
import random
window_size = 32
run_lenght = 32
sampled_symbols = random.sample(list(data.symbol.unique()), 3)
data[data.symbol.isin(sampled_symbols)]
batch_data = []
for symbol in sampled_symbols:
    index = random.randint(window_size+run_lenght, len(data[data.symbol==symbol]))
    selected_data = data[data.symbol==symbol][index-(window_size+run_lenght):index]
    selected_data = selected_data.drop(["symbol","date","year","Key"],axis=1)
    batch_data.append(selected_data)   
batch_data[2]

,open,close,low,high,volume,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,...,Total Assets,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,Earnings Per Share,Estimated Shares Outstanding
114843,61.639999,61.150002,60.889999,61.910000,896600.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
114844,61.230000,62.549999,60.919998,62.709999,875900.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
114845,62.709999,63.049999,62.709999,63.410000,670900.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
114846,62.900002,64.300003,62.720001,64.330002,671500.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
114847,64.150002,64.760002,64.120003,64.839996,616600.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114902,68.190002,68.860001,68.089996,69.150002,665400.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
114903,68.800003,67.879997,67.570000,69.379997,488800.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
114904,67.430000,68.430000,67.160004,68.760002,666300.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
114905,68.029999,68.800003,67.720001,69.029999,591100.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08
114906,69.690002,70.010002,69.180000,70.589996,1260300.0,177860000.0,-52691000.0,-440000.0,24.0,-72990000.0,...,4.438447e+09,1.861310e+09,278699000.0,2.099003e+09,2.339444e+09,4.438447e+09,2.530809e+09,0.0,3.43,1.472507e+08

In [17]:
sampled_symbols = list(data.symbol.unique())
lens = []
for symbol in sampled_symbols:
    lens.append(len(data[data.symbol==symbol]))

In [18]:
min(lens)

126

In [19]:
fit_data = data.drop(["symbol","date","year","Key"], axis=1)
scaler = preprocessing.StandardScaler().fit(fit_data)
selected_data = scaler.transform(batch_data[0])
batch_data[0]

,open,close,low,high,volume,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,...,Total Assets,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,Earnings Per Share,Estimated Shares Outstanding
163888,67.209999,67.900002,67.000000,68.250000,1150200.0,1.418744e+09,-79655000.0,3680000.0,27.0,-132619000.0,...,4.968020e+09,2.794163e+09,1.471875e+09,1.931562e+09,3.036458e+09,4.968020e+09,4.877885e+09,-1.830919e+09,3.79,1.368929e+08
163889,67.889999,67.779999,67.650002,68.650002,754200.0,1.418744e+09,-79655000.0,3680000.0,27.0,-132619000.0,...,4.968020e+09,2.794163e+09,1.471875e+09,1.931562e+09,3.036458e+09,4.968020e+09,4.877885e+09,-1.830919e+09,3.79,1.368929e+08
163890,67.959999,66.839996,66.559998,67.959999,1271900.0,1.418744e+09,-79655000.0,3680000.0,27.0,-132619000.0,...,4.968020e+09,2.794163e+09,1.471875e+09,1.931562e+09,3.036458e+09,4.968020e+09,4.877885e+09,-1.830919e+09,3.79,1.368929e+08
163891,66.529999,67.230003,66.500000,67.470001,879200.0,1.418744e+09,-79655000.0,3680000.0,27.0,-132619000.0,...,4.968020e+09,2.794163e+09,1.471875e+09,1.931562e+09,3.036458e+09,4.968020e+09,4.877885e+09,-1.830919e+09,3.79,1.368929e+08
163892,67.010002,65.760002,65.389999,67.440002,1377600.0,1.418744e+09,-79655000.0,3680000.0,27.0,-132619000.0,...,4.968020e+09,2.794163e+09,1.471875e+09,1.931562e+09,3.036458e+09,4.968020e+09,4.877885e+09,-1.830919e+09,3.79,1.368929e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249627,58.419998,56.950001,56.660000,58.419998,1294000.0,1.288142e+09,50441000.0,-38102000.0,16.0,-181861000.0,...,4.980657e+09,2.475810e+09,1.348576e+09,1.666477e+09,3.314180e+09,4.980657e+09,4.561030e+09,-2.106785e+09,2.01,1.331687e+08
249628,57.529999,58.080002,57.070000,58.290001,928500.0,1.288142e+09,50441000.0,-38102000.0,16.0,-181861000.0,...,4.980657e+09,2.475810e+09,1.348576e+09,1.666477e+09,3.314180e+09,4.980657e+09,4.561030e+09,-2.106785e+09,2.01,1.331687e+08
249629,58.270000,57.209999,56.740002,58.730000,2024500.0,1.288142e+09,50441000.0,-38102000.0,16.0,-181861000.0,...,4.980657e+09,2.475810e+09,1.348576e+09,1.666477e+09,3.314180e+09,4.980657e+09,4.561030e+09,-2.106785e+09,2.01,1.331687e+08
249630,57.000000,57.730000,57.000000,58.259998,953900.0,1.288142e+09,50441000.0,-38102000.0,16.0,-181861000.0,...,4.980657e+09,2.475810e+09,1.348576e+09,1.666477e+09,3.314180e+09,4.980657e+09,4.561030e+09,-2.106785e+09,2.01,1.331687e+08
249631,57.880001,57.189999,56.439999,58.000000,1193300.0,1.288142e+09,50441000.0,-38102000.0,16.0,-181861000.0,...,4.980657e+09,2.475810e+09,1.348576e+09,1.666477e+09,3.314180e+09,4.980657e+09,4.561030e+09,-2.106785e+09,2.01,1.331687e+08

In [20]:
batch_data[0].close.to_numpy()[2]

66.839996

In [21]:
returndata = list(map(lambda x: scaler.transform(x[0:4]),batch_data))

In [22]:
batch_data[0].iloc[[0]].close

163888    67.900002
Name: close, dtype: float64

In [46]:
unique_symbols = pd.unique(data.drop(["date","year","Key"], axis=1).symbol)
np.random.choice(unique_symbols, int(len(unique_symbols)*0.2))

array(['PNR', 'PM', 'NWSA', 'AMAT', 'BBBY', 'SNI', 'WEC', 'CVX', 'LEG',
       'ALB', 'SBUX', 'LUV', 'HST', 'TXT', 'CCI', 'NOV', 'SEE', 'BLL',
       'FMC', 'ETN', 'NOV', 'WYNN', 'NVDA', 'CHK', 'BMY', 'YUM', 'CL',
       'JWN', 'GIS', 'TMO', 'PM', 'TGNA', 'ROP', 'COG', 'SCG', 'WY', 'F',
       'MO', 'M', 'MRO', 'KSS', 'GWW', 'KORS', 'MCO', 'PCAR', 'MMM',
       'MCD', 'DGX', 'XEL', 'ISRG', 'GILD', 'HSIC', 'DG', 'CXO', 'ADBE',
       'UPS', 'ADM', 'LKQ', 'MOS', 'KO', 'VAR', 'WHR', 'EA', 'LLTC',
       'AME', 'APH', 'ILMN', 'D', 'COL', 'HRL', 'FL'], dtype=object)